services:

  frontend:
    build: ./spa
    ports:
      - 80:80
    depends_on:
      - websocket
    deploy:
      replicas: 1

  websocket:
    build: ./chat-websocket
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  chat-filters:
    build: ./chat-filters
    depends_on:
      - redis
      - websocket
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
  redis:
    image: redis:alpine
    command: redis-server --save 3 1
    volumes:
      - db_chatapp:/data

  authentication:
    build: ./auth
    ports:
      - 3001:3001
    environment:
      - EXPRESS_PORT=3001
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_MAX_AGE=3600
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  db_chatapp: