services:
  websocket:
    build: ./chat-websocket
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  chat-filters:
    build: ./chat-filters
    depends_on:
      - redis
      - websocket
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
  redis:
    image: redis:alpine
    command: redis-server --save 3 1
    volumes:
      - db_chatapp:/data

volumes:
  db_chatapp: