services:
  api:
    build: .
    ports:
      - "3000:80"
    environment:
      - EXPRESS_PORT=80
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_MAX_AGE=3600 # In seconds (3600 for 1h)
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
